# Generated by Django 3.2.6 on 2021-09-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bidding_closure_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Administrator role'), (2, 'User role')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('bid_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('automatic', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction_backend.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_bids', to='auction_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticBidItem',
            fields=[
                ('automatic_bid_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_bid_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bid_items', models.ManyToManyField(blank=True, to='auction_backend.BidItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_bids', to='auction_backend.user')),
            ],
        ),
    ]
